"""Blood centre side: Outlook, Requests (a request before and after sending), Bookings, Notifications.

The centre never gets names out of the matching step: it sees a count. A name appears only through
store.request_bookings, which is fed by people who actually booked a slot.
"""

from __future__ import annotations

from datetime import date, timedelta

import streamlit as st

import store
import ui

PAGES = ["Outlook", "Data", "Requests", "Bookings", "Network", "Hospital orders", "Notifications"]
PLACE = "rbc"                                  # default; render() switches it to the signed-in account's own centre
PLACE_NAME = store.PLACES[PLACE]["name"]
SIM_DAYS = 5                                   # store's response curve, generated by BloodSight AI, runs five days
SLOT_TIMES = ["09:00", "13:00", "16:30"]       # a few times a day
RADIUS_OPTIONS = [10, 25, 50]
TYPES = store.BLOOD_TYPES + [store.ANY_TYPE]

# Status marks for a request: a dot and plain coloured text, never a pill.
_STATUS = {"draft": ("#6b7280", "Draft"),
           "sent": ("#1d4ed8", "Sent"),
           "closed": ("#15803d", "Closed")}


# ------------------------------------------------------------------------- formatting helpers

def _day(value: str | date) -> str:
    """2026-09-22 -> Tue 22 Sep."""
    d = value if isinstance(value, date) else date.fromisoformat(str(value)[:10])
    return f"{d:%a %d %b}".replace(" 0", " ")


def _slot(value: str) -> str:
    """2026-09-22 16:30 -> Tue 22 Sep · 16:30, in store's shared wording. Guarded for a request without slots."""
    return store.slot_label(value) if len(value) >= 16 else value


def _slot_options(days: int, times: list[str] | None = None) -> list[str]:
    """The next `days` days, a few times a day, as "YYYY-MM-DD HH:MM"."""
    start = store.today()
    return [f"{(start + timedelta(days=d)).isoformat()} {t}"
            for d in range(1, days + 1) for t in (times if times is not None else SLOT_TIMES)]


def _message(blood_type: str, slots: list[str]) -> str:
    """The pre-written text people read. Editable afterwards."""
    what = "plasma" if blood_type == store.ANY_TYPE else f"{blood_type} blood"
    head = f"The {PLACE_NAME} expects to run short of {what} next week. You can help prevent it"
    if not slots:
        return f"{head}."
    days = sorted({s[:10] for s in slots})
    span = _day(days[0]) if len(days) == 1 else f"{_day(days[0])} to {_day(days[-1])}"
    return f"{head}: slots from {span}."


def _order(req: dict) -> int:
    """Newest first: REQ-10 is newer than REQ-9, so sort on the number, not the string."""
    return int(req["id"].split("-")[-1])


def _mark(color: str, label: str) -> str:
    """A status mark: 6px dot, then plain coloured text. No pill, no tint, no border."""
    return (f'<span style="display:inline-flex;align-items:center;gap:6px;font-size:12.5px;font-weight:600;'
            f'color:{color}"><span style="width:6px;height:6px;border-radius:50%;background:{color};'
            f'display:inline-block"></span>{label}</span>')


def _chip(status: str) -> str:
    color, label = _STATUS.get(status, _STATUS["draft"])
    return _mark(color, label)


def _h(text: str) -> None:
    st.markdown(f'<div class="bsx-h">{text}</div>', unsafe_allow_html=True)


def _rules(blood_type: str, radius: int) -> str:
    type_rule = "any blood type (plasma)" if blood_type == store.ANY_TYPE else f"blood type {blood_type}"
    return (f"Matched on: {type_rule}, home within {radius} km, agreed to be asked, "
            f"last gave {store.MIN_DAYS_BETWEEN_DONATIONS} or more days ago, "
            f"asked fewer than {store.MAX_ASKS_PER_MONTH} times this month.")


_PLAIN = 'style="text-align:left;font-weight:400"'          # bs-rec makes the last cell bold and right


# Fixed widths so the columns line up from one request's table to the next down the Bookings page.
_COLS = ('<colgroup><col style="width:22%"><col style="width:18%"><col style="width:11%">'
         '<col style="width:34%"><col style="width:15%"></colgroup>')

# Every table on this screen: full width, fixed layout, and cells that do not hug the left edge.
_GRID_CSS = """<style>
.bs-rec {padding: 16px 18px;}
.bs-rec table {width: 100%; table-layout: fixed; border-collapse: collapse; font-size: 13px;}
.bs-rec table td {padding: 8px 12px; vertical-align: top; word-break: break-word; border-top: 1px solid #e5e4df; color: #4b5563; font-weight: 400;}
.bs-rec table td:first-child {padding-left: 0;}
.bs-rec table td:last-child {padding-right: 0; text-align: right; font-weight: 600; color: #111827;}
.bs-rec table tr:first-child td {border-top: none;}
.bs-rec table tr.hd td {font-size: 11.5px; font-weight: 600; color: #6b7280; text-align: left;}
.bsx-h {font-size: 15px; font-weight: 600; color: #111827; margin: 24px 0 8px;}
.bsx-strip {display: grid; grid-template-columns: repeat(4, 1fr); border: 1px solid #e5e4df; border-radius: 10px; background: #fff; margin: 4px 0 10px;}
.bsx-strip > div {padding: 10px 14px; border-left: 1px solid #e5e4df;}
.bsx-strip > div:first-child {border-left: none;}
.bsx-strip .l {font-size: 12px; color: #6b7280;}
.bsx-strip .v {font-size: 24px; font-weight: 600; color: #111827; line-height: 1.3;}
.bsx-note {font-size: 12.5px; color: #4b5563;}
</style>"""

MANY = 100000                                  # "show everything": no booking is ever hidden behind a count


def _grid_css() -> None:
    st.markdown(_GRID_CSS, unsafe_allow_html=True)


def _booked_by(b: dict) -> str:
    return _mark("#1d4ed8", "App account") if b["real"] else _mark("#6b7280", "BloodSight AI")


def _booking_table(named: list[dict]) -> str:
    head = (f'<tr class="hd"><td>Slot</td><td>Name</td><td>Blood type</td>'
            f'<td>Note</td><td {_PLAIN}>Booked by</td></tr>')
    rows = "".join(
        f"<tr><td>{_slot(b['slot'])}</td><td><b>{b['name']}</b></td><td>{b['blood_type'] or ''}</td>"
        f"<td>{b['note']}</td><td {_PLAIN}>{_booked_by(b)}</td></tr>"
        for b in named)
    return (f'<div class="bs-rec" style="margin-bottom:8px">'
            f'<table style="table-layout:fixed">{_COLS}{head}{rows}</table></div>')


def _all_bookings(req_id: str) -> dict:
    """Every booking of a request. Nothing is summarised away into an "N more"."""
    return store.request_bookings(req_id, sample=MANY)


def _booking_block(named: list[dict]) -> None:
    """The full table, in a scrolling container once it gets long."""
    if len(named) > 8:
        with st.container(height=420):
            st.markdown(_booking_table(named), unsafe_allow_html=True)
    else:
        st.markdown(_booking_table(named), unsafe_allow_html=True)


# ------------------------------------------------------------------------------ new request form

FORM_KEYS = ("req_note", "req_seed", "req_days", "req_bt", "req_radius", "req_target", "req_times",
             "req_message", "req_message_auto")


def _init_form() -> None:
    """Seed the form, and fill it from the outlook recommendation when one was handed over.

    Streamlit drops the state of widgets that a run did not draw, so the recommendation is also kept
    in "req_seed": leaving the page and coming back must not quietly change the target under the caption.
    """
    pre = st.session_state.pop("request_prefill", None)
    if pre:
        window = min(max(int(pre.get("window") or 5), 3), 7)
        st.session_state["req_seed"] = {"days": window, "bt": pre["blood_type"], "target": int(pre["target"])}
        st.session_state["req_note"] = (f"Filled in from the recommendation: {int(pre['target'])} donations "
                                        f"in {window} days.")
        for k in ("req_days", "req_bt", "req_target", "req_message", "req_message_auto"):
            st.session_state.pop(k, None)               # the seed below fills these in again
    seed = st.session_state.get("req_seed", {})
    st.session_state.setdefault("req_days", seed.get("days", SIM_DAYS))
    st.session_state.setdefault("req_bt", seed.get("bt", "O-"))
    st.session_state.setdefault("req_radius", 25)
    st.session_state.setdefault("req_target", str(seed.get("target", 200)))
    st.session_state.setdefault("req_times", list(SLOT_TIMES))


def _clear_form() -> None:
    """A created request leaves the form on its own default: the recommendation has been acted on."""
    for k in FORM_KEYS:
        st.session_state.pop(k, None)


MAX_TARGET = 2000


def _target(text: str) -> int | None:
    """The typed target as a whole number, or None when it is not one.

    A number_input silently keeps its old value when staff type something out of range, so the request
    would be sent with a target nobody chose. Here what is sent is what is on screen, or nothing is sent.
    """
    try:
        n = int(str(text).strip())
    except ValueError:
        return None
    return n if 1 <= n <= MAX_TARGET else None


def _open_notice(req: dict) -> str:
    """Why a second request of the same type is refused, in the words of the request that is already open."""
    s = store.request_stats(req["id"])
    return (f"{req['id']} for {req['blood_type']} is open: day {min(req['day'], SIM_DAYS)} of {SIM_DAYS}, "
            f"{s['booked']:,} of {req['target']:,} booked. Close it before sending another.")


def _new_request_form(user: dict) -> None:
    _init_form()
    if st.session_state.get("req_note"):
        st.caption(st.session_state["req_note"])

    left, right = st.columns([1.35, 1], gap="large")
    with left:
        c1, c2 = st.columns(2)
        blood_type = c1.selectbox("Blood type", TYPES, key="req_bt")
        radius = c2.radio("How far from the centre", RADIUS_OPTIONS, key="req_radius", horizontal=True,
                          format_func=lambda km: f"{km} km")
        c3, c4 = st.columns(2)
        days = c3.slider("Slots: days from tomorrow", 3, 7, key="req_days")
        times = c4.multiselect("Times a day", SLOT_TIMES, key="req_times")
        slots = _slot_options(days, times)
        st.caption(f"{len(slots)} slots offered: {_day(store.today() + timedelta(days=1))} to "
                   f"{_day(store.today() + timedelta(days=days))}"
                   + (f", at {', '.join(times)}." if times else ". Choose at least one time."))
        target = _target(st.text_input("Target donations", key="req_target",
                                       help=f"A whole number of donations, from 1 to {MAX_TARGET:,}."))
        if target is None:
            st.caption(f"Target donations must be a whole number from 1 to {MAX_TARGET:,}.")
        # The text is regenerated when the blood type or the slots change, unless staff edited it by hand.
        auto = _message(blood_type, slots)
        if st.session_state.get("req_message", st.session_state.get("req_message_auto")) \
                == st.session_state.get("req_message_auto"):
            st.session_state["req_message"] = auto
        st.session_state["req_message_auto"] = auto
        message = st.text_area("The message people read", key="req_message", height=110)

    with right:
        m = store.match_count(blood_type, radius)
        _h("Who gets it")
        st.markdown(
            f'<div class="bs-rec"><div style="font-size:15px;font-weight:600;color:#111827;margin-bottom:4px">'
            f'{m["total"]:,} people match</div><table>'
            f'<tr><td>Patients of {store.LAB_NAME}</td><td>{m["patients"]:,}</td></tr>'
            f'<tr><td>Gave at this centre before</td><td>{m["gave_before"]:,}</td></tr>'
            f'<tr><td>Expected bookings</td><td>about {m["expected_bookings"]:,}</td></tr></table></div>',
            unsafe_allow_html=True)
        st.caption(_rules(blood_type, radius))
        st.caption(f"Expected bookings: about {store.EXPECTED_BOOKING_RATE:.0%} of the people asked.")
        st.markdown('<div class="bsx-note">Names appear only after a booking.</div>', unsafe_allow_html=True)

    # One open request per blood type: a second one would ask the same people twice and count them twice.
    already_open = store.open_request(PLACE, blood_type)
    if already_open:
        st.warning(_open_notice(already_open))

    b1, b2, _ = st.columns([1.2, 1, 2.2])
    problem = ("Choose at least one slot." if not slots else
               "Write the message people read." if not message.strip() else
               f"Set a target of at least 1 donation, at most {MAX_TARGET:,}." if target is None else None)
    if b1.button(f"Send request to {m['total']:,} people", type="primary", key="send_new",
                 disabled=already_open is not None,
                 help=_open_notice(already_open) if already_open else None):
        if problem:
            st.error(problem)
        else:
            try:
                req = store.create_request(user["username"], PLACE, blood_type, radius, slots,
                                           int(target), message.strip(), send=True)
            except ValueError as e:
                st.error(str(e))
            else:
                st.session_state["req_flash"] = f"{req['id']} sent to {req['matched']['total']:,} people."
                _clear_form()
                st.rerun()
    if b2.button("Save draft", key="save_draft"):
        if problem:
            st.error(problem)
        else:
            try:
                req = store.create_request(user["username"], PLACE, blood_type, radius, slots,
                                           int(target), message.strip(), send=False)
            except ValueError as e:
                st.error(str(e))
            else:
                st.session_state["req_flash"] = f"{req['id']} saved as a draft."
                _clear_form()
                st.rerun()


# --------------------------------------------------------------------------------- request list

def _request_card(req: dict) -> None:
    stats = store.request_stats(req["id"])
    with st.container(border=True):
        head, chip = st.columns([3, 1], vertical_alignment="center")
        head.markdown(f"**{req['blood_type']} · {req['id']}** · target {req['target']} donations")
        chip.markdown(f"<div style='text-align:right'>{_chip(req['status'])}</div>", unsafe_allow_html=True)
        sent = f"sent {_day(req['sent_at'])} {req['sent_at'][11:16]}" if req.get("sent_at") else "not sent yet"
        st.caption(f"Within {req['radius_km']} km · {len(req['slots'])} slots · {sent}")

        if req["status"] == "draft":
            st.caption(f"{req['matched']['total']:,} people match. Nobody has been asked yet.")
            if st.button(f"Send request to {req['matched']['total']:,} people", type="primary",
                         key=f"send_{req['id']}"):
                try:
                    store.send_request(req["id"])
                except ValueError as e:
                    st.error(str(e))
                else:
                    st.session_state["req_flash"] = f"{req['id']} sent."
                    st.rerun()
            return

        st.markdown(f'<div class="bsx-note">Day {min(req["day"], SIM_DAYS)} of {SIM_DAYS}</div>',
                    unsafe_allow_html=True)
        counts = (("Asked", stats["asked"]), ("Seen", stats["seen"]),
                  ("Booked", stats["booked"]), ("Not this time", stats["not_this_time"]))
        st.markdown('<div class="bsx-strip">'
                    + "".join(f'<div><div class="l">{l}</div><div class="v">{v:,}</div></div>' for l, v in counts)
                    + "</div>", unsafe_allow_html=True)
        # The bar stops at full; the text keeps the true numbers, so an over-target request reads honestly.
        st.progress(min(stats["booked"] / max(req["target"], 1), 1.0),
                    text=f"{stats['booked']:,} of {req['target']:,} booked"
                         + (" · target reached" if stats["booked"] >= req["target"] else ""))

        bk = _all_bookings(req["id"])
        if bk["named"]:
            st.caption(f"All {len(bk['named']):,} bookings on this request.")
            _booking_block(bk["named"])
        else:
            st.caption("No bookings yet. A name appears only when someone books a slot.")

        if req["status"] == "closed":
            if req.get("closed_reason") == "target reached":
                st.success(f"Target reached: {stats['booked']:,} booked, target {req['target']:,}. "
                           "The request closed itself.")
            else:
                st.caption(f"Closed: {req.get('closed_reason', 'closed by staff')}.")
            return
        # What closing does, before the click: it stops new bookings, it does not undo the ones already made.
        close_help = "Closing stops new bookings. Booked appointments are kept."
        st.caption(close_help)
        a1, a2, _ = st.columns([1, 1, 2.6])
        if a1.button("Advance one day", key=f"day_{req['id']}",
                     help="Moves this request one day forward in the response curve.",
                     disabled=req["day"] >= SIM_DAYS):
            store.advance_day(req["id"])
            st.rerun()
        if a2.button("Close request", key=f"close_{req['id']}", help=close_help):
            store.close_request(req["id"])
            st.session_state["req_flash"] = (f"{req['id']} closed. It disappears from everyone's Needs. "
                                             "The appointments already booked on it stand.")
            st.rerun()


def _requests_page(user: dict, flash: str | None) -> None:
    ui.header("Requests")
    _grid_css()
    if flash:
        st.success(flash)
    _h("New request")
    with st.container(border=True):
        _new_request_form(user)
    _h("This centre's requests")
    mine = sorted(store.requests(PLACE), key=_order, reverse=True)      # newest first
    if not mine:
        st.caption("No requests yet.")
        return
    for req in mine:
        _request_card(req)


# -------------------------------------------------------------------------------- bookings page

def _bookings_page() -> None:
    ui.header("Bookings", "Names appear only after a booking.")
    _grid_css()
    live = [r for r in store.requests(PLACE) if r["status"] != "draft"]
    if not live:
        st.caption("No request has been sent yet.")
        return
    for req in sorted(live, key=_order, reverse=True):
        bk = _all_bookings(req["id"])
        _h(f"{req['blood_type']} · {req['id']} · {bk['total']:,} booked")
        if not bk["named"]:
            st.caption("No bookings yet.")
            continue
        _booking_block(bk["named"])


# --------------------------------------------------------------------------------- network page

_KIND_COLOR = {"blood centre": "#2a78d6", "hospital": "#1baf7a", "donor centre": "#b97d00"}


def _network_map(sites: list[dict]):
    """A map of the regional network. Plotly renamed the map traces, so both spellings are supported."""
    import plotly.graph_objects as go

    trace, layout = None, None
    if hasattr(go, "Scattermap"):
        trace, layout = go.Scattermap, "map"
    else:                                                       # older Plotly: the mapbox spelling
        trace, layout = go.Scattermapbox, "mapbox"
    fig = go.Figure()
    for kind, color in _KIND_COLOR.items():
        group = [s for s in sites if s["kind"] == kind]
        if not group:
            continue
        fig.add_trace(trace(
            lat=[s["lat"] for s in group], lon=[s["lon"] for s in group], mode="markers+text",
            marker=dict(size=15, color=color), name=kind.capitalize(),
            text=[s["name"] for s in group], textposition="top right",
            textfont=dict(size=11, color=ui.INK),
            hovertext=[f"{s['name']} ({s['kind']})" for s in group], hoverinfo="text"))
    centre_view = dict(center=dict(lat=51.05, lon=5.9), zoom=8)
    style = {"style": "open-street-map"} if layout == "map" else {"style": "open-street-map"}
    fig.update_layout(**{layout: {**centre_view, **style}},
                      height=480, margin=dict(l=0, r=0, t=0, b=0),
                      legend=dict(orientation="h", yanchor="bottom", y=1.01, xanchor="left", x=0))
    return fig


def _network_page(user: dict) -> None:
    ui.header("Network", "Blood centres and hospitals of the region.")
    _grid_css()
    sites = store.network_map()
    st.plotly_chart(_network_map(sites), use_container_width=True, config={"displayModeBar": False})

    left, right = st.columns([1, 1.15], gap="large")
    with left:
        _h("Sites in the network")
        rows = "".join(
            f'<tr><td><b>{s["name"]}</b></td><td>{s["kind"].capitalize()}</td>'
            f'<td style="text-align:left;font-weight:400">{s["lat"]:.3f}, {s["lon"]:.3f}</td></tr>'
            for s in sites)
        st.markdown(
            '<div class="bs-rec"><table><tr class="hd"><td>Site</td><td>Kind</td>'
            f'<td {_PLAIN}>Position</td></tr>{rows}</table></div>', unsafe_allow_html=True)

    with right:
        _h("Notify the network")
        with st.form("network_notice", border=True):
            c1, c2 = st.columns(2)
            kind = c1.selectbox("Kind of notice", ["Deficiency", "Surplus"], key="net_kind")
            bt = c2.selectbox("Blood type", store.BLOOD_TYPES, key="net_bt")
            units = st.number_input("Units", min_value=1, max_value=5000, value=50, step=10, key="net_units")
            note = st.text_area("Note for the other centres", key="net_note", height=90,
                                placeholder="What is needed or available, and by when.")
            if st.form_submit_button("Send notice", type="primary", use_container_width=True):
                notice = store.send_network_notice(user["username"], kind.lower(), bt, int(units), note.strip())
                st.session_state["net_flash"] = notice["id"]
                st.rerun()
        st.caption("A notice reaches every blood centre account. Other sites of the region are listed as informed.")

    sent = st.session_state.pop("net_flash", None)
    if sent:
        st.success(f"{sent} sent to the network.")

    _h("Notices")
    notices = store.network_notices()
    if not notices:
        st.caption("No notice has been sent yet.")
        return
    for n in notices:
        word = "needs" if n["kind"] == "deficiency" else "can spare"
        with st.container(border=True):
            head, chip = st.columns([3, 1], vertical_alignment="center")
            head.markdown(f"**{n['id']} · {n['from_org'] or n['from_place']} {word} "
                          f"{n['units']:,} units of {n['blood_type']}**")
            chip.markdown(f"<div style='text-align:right'>{_chip('sent')}</div>", unsafe_allow_html=True)
            if n.get("note"):
                st.markdown(n["note"])
            st.caption(f"{_day(n['created_at'])} {n['created_at'][11:16]} · informed: "
                       + ", ".join(n["informed"]))


# -------------------------------------------------------------------------- hospital orders page

def _order_card(user: dict, o: dict) -> None:
    with st.container(border=True):
        head, chip = st.columns([3, 1], vertical_alignment="center")
        head.markdown(f"**{o['id']} · {o['units']} x {o['blood_type']} {o['component'].lower()}** "
                      f"for {o['from_org']}")
        chip.markdown(f"<div style='text-align:right'>{_mark('#1d4ed8', o['status'].capitalize())}</div>",
                      unsafe_allow_html=True)
        st.caption(f"Needed by {_day(o['needed_by'])}"
                   + (f" · {o['procedure']}" if o.get("procedure") else "")
                   + f" · submitted {_day(o['created_at'])} {o['created_at'][11:16]}")
        if o.get("note"):
            st.markdown(f"*{o['note']}*")

        c1, c2 = st.columns([1, 1], gap="large")
        with c1:
            st.markdown("**Answer this order**")
            status = st.selectbox("Status", store.ORDER_STATUSES, key=f"st_{o['id']}",
                                  index=store.ORDER_STATUSES.index(o["status"]))
            note = st.text_input("Note for the sender", key=f"stn_{o['id']}")
            if st.button("Set status", key=f"setst_{o['id']}", type="primary"):
                store.update_order(o["id"], status, user["username"], note.strip())
                st.session_state["ord_flash"] = f"{o['id']} set to {status}."
                st.rerun()
            st.markdown("**Status history**")
            for h in o["history"]:
                st.caption(f"{_day(h['at'])} {h['at'][11:16]} · {h['status']} · {h['by']}"
                           + (f" · {h['note']}" if h.get("note") else ""))
        with c2:
            st.markdown("**Messages**")
            if o["messages"]:
                with st.container(height=200):
                    for m in o["messages"]:
                        st.markdown(f"**{m['by']}** · {_day(m['at'])} {m['at'][11:16]}")
                        st.markdown(m["text"])
            else:
                st.caption("No messages on this order yet.")
            reply = st.text_area("Reply", key=f"msg_{o['id']}", height=90)
            if st.button("Send reply", key=f"send_msg_{o['id']}"):
                if reply.strip():
                    store.order_message(o["id"], user["username"], reply.strip())
                    st.session_state["ord_flash"] = f"Reply sent on {o['id']}."
                    st.rerun()
                else:
                    st.error("Write a reply first.")


def _orders_page(user: dict) -> None:
    ui.header("Hospital orders", "Blood ordered from this centre by hospitals and labs.")
    _grid_css()
    flash = st.session_state.pop("ord_flash", None)
    if flash:
        st.success(flash)
    items = store.orders(to_place=PLACE)

    _h("Supply constraint notice")
    with st.container(border=True):
        c1, c2 = st.columns([1, 3], gap="large")
        bt = c1.selectbox("Blood type", store.BLOOD_TYPES, key="sc_bt")
        text = c2.text_input("Notice", key="sc_text",
                             placeholder="Red cells O- are rationed until Friday: urgent cases first.")
        if st.button("Send notice", key="sc_send", type="primary"):
            if text.strip():
                n = store.supply_constraint_notice(user["username"], bt, text.strip())
                st.success(f"Supply constraint on {bt} sent to {n} account{'s' if n != 1 else ''}.")
            else:
                st.error("Write the notice first.")

    if not items:
        st.caption("No hospital or lab has ordered from this centre yet.")
        return

    _h("All orders")
    rows = "".join(
        f'<tr><td>{o["id"]}</td><td>{o["from_org"]}</td><td>{o["component"]}</td><td>{o["blood_type"]}</td>'
        f'<td>{o["units"]:,}</td><td>{_day(o["needed_by"])}</td><td>{o.get("procedure") or ""}</td>'
        f'<td {_PLAIN}>{o["status"].capitalize()}</td></tr>' for o in items)
    table = ('<div class="bs-rec"><table><tr class="hd"><td>Order</td><td>From</td>'
             '<td>Component</td><td>Blood type</td><td>Units</td><td>Needed by</td><td>Planned procedure</td>'
             f'<td {_PLAIN}>Status</td></tr>{rows}</table></div>')
    if len(items) > 8:
        with st.container(height=420):
            st.markdown(table, unsafe_allow_html=True)
    else:
        st.markdown(table, unsafe_allow_html=True)

    _h("Answer an order")
    for o in items:
        _order_card(user, o)


# ------------------------------------------------------------------------------------- render

def render(user: dict) -> None:
    # The screen belongs to the centre of the signed-in account, so a second centre account works too.
    global PLACE, PLACE_NAME
    PLACE = user.get("org") or PLACE
    PLACE_NAME = store.PLACES.get(PLACE, {}).get("name", user.get("title") or PLACE)
    page = ui.sidebar(user, PAGES)          # the outlook's handover jumps here through ui.sidebar's "_goto"
    flash = st.session_state.pop("req_flash", None)
    if page == "Outlook":
        from views import outlook
        ui.header("BloodSight AI")
        outlook.render(user)
    elif page == "Data":
        from views import data
        data.render(user)
    elif page == "Requests":
        _requests_page(user, flash)
    elif page == "Bookings":
        _bookings_page()
    elif page == "Network":
        _network_page(user)
    elif page == "Hospital orders":
        _orders_page(user)
    else:
        ui.header("Notifications")
        ui.notification_list(user["username"], "Nothing yet. Bookings and answers arrive here.")
